"""
Pokewalker Data Structures

Python dataclasses representing the data structures used by the
Pokewalker, as reverse-engineered by dmitry.gr.

All multi-byte values are little-endian unless otherwise specified.
"""

import struct
from dataclasses import dataclass, field
from typing import Optional
from enum import IntEnum, IntFlag


class IdentityFlags(IntFlag):
    """Flags in IdentityData.flags field."""
    WALKER_PAIRED = 0x01      # Walker paired to game
    HAS_POKEMON = 0x02        # Walker has a pokemon
    POKEMON_ON_WALK = 0x04    # Pokemon joined us on a walk


class RouteImageIndex(IntEnum):
    """Route background image indices."""
    FIELD_AND_TREES = 0
    FOREST_AND_TREES = 1
    SUBURBS = 2
    URBAN = 3
    HILL_AND_VOLCANO = 4
    DIM_CAVE = 5
    LAKE = 6
    BEACH_AND_WAVES = 7


class LogEventType(IntEnum):
    """Event log entry types."""
    EMPTY = 0
    PEER_PLAY_1 = 1
    PEER_PLAY_2 = 2
    PEER_PLAY_3 = 3
    PEER_PLAY_4 = 4
    PEER_PLAY_5 = 5
    PEER_PLAY_6 = 6
    PEER_PLAY_7 = 7
    PEER_PLAY_8 = 8
    PEER_PLAY_9 = 9
    PEER_PLAY_10 = 10
    ITEM_DOWSED = 11
    ITEM_DOWSED_SPECIAL = 12
    POKE_RADAR_CAUGHT = 13
    POKE_RADAR_CAUGHT_SPECIAL = 14
    POKE_RADAR_RAN_AWAY = 15
    POKE_RADAR_LOST = 16
    POKE_FOUND_ITEM = 17
    MOOD_HAPPY_SKIPPING = 18
    MOOD_RUNNING_CIRCLES = 19
    MOOD_LOOKING_AWAY = 20
    MOOD_BORED_ANGRY = 21
    MOOD_WANTS_HOME = 22
    POKE_JOINED = 23
    WALK_ENDED = 24
    WALK_STARTED = 25
    PLAYED_LOT_CONTENT = 26
    FELL_ASLEEP = 27
    ITEM_GIFTED = 28


def decode_pokemon_string(data: bytes, max_chars: int = 11) -> str:
    """
    Decode a Pokemon game string (16-bit characters).
    
    Pokemon games use a proprietary 16-bit character encoding.
    This is a simplified decoder for ASCII-compatible characters.
    """
    chars = []
    for i in range(0, min(len(data), max_chars * 2), 2):
        if i + 1 >= len(data):
            break
        code = struct.unpack("<H", data[i:i+2])[0]
        if code == 0xFFFF or code == 0x0000:
            break
        # Simplified mapping - Pokemon gen 4 uses a custom encoding
        # This handles basic ASCII range
        if 0x0001 <= code <= 0x00FF:
            chars.append(chr(code))
        elif code == 0x0000:
            break
        else:
            # For non-ASCII, use placeholder
            chars.append("?")
    return "".join(chars)


def encode_pokemon_string(text: str, max_chars: int = 11) -> bytes:
    """
    Encode a string to Pokemon game format (16-bit characters).
    
    Returns bytes padded to max_chars * 2.
    """
    result = bytearray()
    for i, char in enumerate(text[:max_chars]):
        code = ord(char) if ord(char) < 256 else 0x003F  # '?' for unknown
        result.extend(struct.pack("<H", code))
    
    # Pad with terminator
    while len(result) < max_chars * 2:
        result.extend(struct.pack("<H", 0xFFFF))
    
    return bytes(result)


@dataclass
class UniqueIdentityData:
    """
    Unique identity data (0x28 bytes).
    Generated by the DS game at pairing time.
    
    EEPROM: 0x0083-0x00AB (reliable copy at 0x0183)
    """
    data: bytes = field(default_factory=lambda: bytes(0x28))
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "UniqueIdentityData":
        if len(data) < 0x28:
            data = data + bytes(0x28 - len(data))
        return cls(data=data[:0x28])
    
    def to_bytes(self) -> bytes:
        return self.data[:0x28].ljust(0x28, b"\x00")


@dataclass
class IdentityData:
    """
    Walker identity data (0x68 bytes).
    
    Stored reliably at EEPROM: 0x00ED/0x01ED
    Returned by CMD_20/CMD_22.
    """
    unk_0: int = 0               # LE, always 1?
    unk_1: int = 0               # LE, always 1?
    unk_2: int = 0               # LE, always 7?
    unk_3: int = 0               # LE, always 7?
    trainer_tid: int = 0         # Trainer ID
    trainer_sid: int = 0         # Secret ID
    unique_id: UniqueIdentityData = field(default_factory=UniqueIdentityData)
    event_bitmap: bytes = field(default_factory=lambda: bytes(0x10))
    trainer_name: str = ""       # 8 chars max
    unk_4: int = 0
    unk_5: int = 0
    unk_6: int = 0
    flags: int = 0               # IdentityFlags
    proto_ver: int = 0x02        # Protocol version
    unk_7: int = 0
    proto_subver: int = 0x00     # Protocol subversion
    unk_8: int = 0
    last_sync_time: int = 0      # Big endian!
    step_count: int = 0          # Big endian!
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "IdentityData":
        """Parse identity data from 0x68 bytes."""
        if len(data) < 0x68:
            raise ValueError(f"IdentityData needs 0x68 bytes, got {len(data)}")
        
        return cls(
            unk_0=struct.unpack("<I", data[0x00:0x04])[0],
            unk_1=struct.unpack("<I", data[0x04:0x08])[0],
            unk_2=struct.unpack("<H", data[0x08:0x0A])[0],
            unk_3=struct.unpack("<H", data[0x0A:0x0C])[0],
            trainer_tid=struct.unpack("<H", data[0x0C:0x0E])[0],
            trainer_sid=struct.unpack("<H", data[0x0E:0x10])[0],
            unique_id=UniqueIdentityData.from_bytes(data[0x10:0x38]),
            event_bitmap=data[0x38:0x48],
            trainer_name=decode_pokemon_string(data[0x48:0x58], 8),
            unk_4=data[0x58],
            unk_5=data[0x59],
            unk_6=data[0x5A],
            flags=data[0x5B],
            proto_ver=data[0x5C],
            unk_7=data[0x5D],
            proto_subver=data[0x5E],
            unk_8=data[0x5F],
            last_sync_time=struct.unpack(">I", data[0x60:0x64])[0],
            step_count=struct.unpack(">I", data[0x64:0x68])[0],
        )
    
    def to_bytes(self) -> bytes:
        """Serialize to 0x68 bytes."""
        data = bytearray(0x68)
        
        struct.pack_into("<I", data, 0x00, self.unk_0)
        struct.pack_into("<I", data, 0x04, self.unk_1)
        struct.pack_into("<H", data, 0x08, self.unk_2)
        struct.pack_into("<H", data, 0x0A, self.unk_3)
        struct.pack_into("<H", data, 0x0C, self.trainer_tid)
        struct.pack_into("<H", data, 0x0E, self.trainer_sid)
        data[0x10:0x38] = self.unique_id.to_bytes()
        data[0x38:0x48] = self.event_bitmap[:0x10].ljust(0x10, b"\x00")
        data[0x48:0x58] = encode_pokemon_string(self.trainer_name, 8)
        data[0x58] = self.unk_4
        data[0x59] = self.unk_5
        data[0x5A] = self.unk_6
        data[0x5B] = self.flags
        data[0x5C] = self.proto_ver
        data[0x5D] = self.unk_7
        data[0x5E] = self.proto_subver
        data[0x5F] = self.unk_8
        struct.pack_into(">I", data, 0x60, self.last_sync_time)
        struct.pack_into(">I", data, 0x64, self.step_count)
        
        return bytes(data)
    
    @property
    def is_paired(self) -> bool:
        return bool(self.flags & IdentityFlags.WALKER_PAIRED)
    
    @property
    def has_pokemon(self) -> bool:
        return bool(self.flags & IdentityFlags.HAS_POKEMON)
    
    @property
    def pokemon_on_walk(self) -> bool:
        return bool(self.flags & IdentityFlags.POKEMON_ON_WALK)


@dataclass
class HealthData:
    """
    Walker health/stats data (0x19 bytes).
    
    Stored reliably at EEPROM: 0x0156/0x0256
    Cached in RAM at 0xF780.
    All values are big-endian.
    """
    lifetime_total_steps: int = 0
    today_steps: int = 0          # Zeroed at midnight
    last_sync_time: int = 0
    total_days: int = 0
    current_watts: int = 0
    unk_0: int = 0
    unk_1: int = 0
    unk_2: int = 0
    settings: int = 0             # Bits: [0]=special route, [1..2]=volume, [3..6]=contrast
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "HealthData":
        """Parse health data from bytes."""
        if len(data) < 0x19:
            raise ValueError(f"HealthData needs 0x19 bytes, got {len(data)}")
        
        return cls(
            lifetime_total_steps=struct.unpack(">I", data[0x00:0x04])[0],
            today_steps=struct.unpack(">I", data[0x04:0x08])[0],
            last_sync_time=struct.unpack(">I", data[0x08:0x0C])[0],
            total_days=struct.unpack(">H", data[0x0C:0x0E])[0],
            current_watts=struct.unpack(">H", data[0x0E:0x10])[0],
            unk_0=struct.unpack(">H", data[0x10:0x12])[0],
            unk_1=data[0x12],
            unk_2=data[0x13],
            # 3 bytes padding at 0x14-0x16
            settings=data[0x17] if len(data) > 0x17 else 0,
        )
    
    def to_bytes(self) -> bytes:
        """Serialize to 0x19 bytes."""
        data = bytearray(0x19)
        
        struct.pack_into(">I", data, 0x00, self.lifetime_total_steps)
        struct.pack_into(">I", data, 0x04, self.today_steps)
        struct.pack_into(">I", data, 0x08, self.last_sync_time)
        struct.pack_into(">H", data, 0x0C, self.total_days)
        struct.pack_into(">H", data, 0x0E, self.current_watts)
        struct.pack_into(">H", data, 0x10, self.unk_0)
        data[0x12] = self.unk_1
        data[0x13] = self.unk_2
        # Padding at 0x14-0x16
        data[0x17] = self.settings
        
        return bytes(data)
    
    @property
    def volume(self) -> int:
        """Get volume setting (0-3)."""
        return (self.settings >> 1) & 0x03
    
    @property
    def contrast(self) -> int:
        """Get contrast setting (0-15)."""
        return (self.settings >> 3) & 0x0F
    
    @property
    def on_special_route(self) -> bool:
        """Check if on special route."""
        return bool(self.settings & 0x01)


@dataclass
class PokemonSummary:
    """
    Pokemon summary data (0x10 bytes).
    Used for caught/held pokemon and route-available pokemon.
    All values are little-endian.
    """
    species: int = 0
    held_item: int = 0
    moves: list[int] = field(default_factory=lambda: [0, 0, 0, 0])
    level: int = 0
    variant_and_flags: int = 0  # Low 5 bits: variant, mask 0x20: female
    more_flags: int = 0         # 0x02: shiny, 0x01: has form
    padding: int = 0
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "PokemonSummary":
        """Parse from 0x10 bytes."""
        if len(data) < 0x10:
            raise ValueError(f"PokemonSummary needs 0x10 bytes, got {len(data)}")
        
        return cls(
            species=struct.unpack("<H", data[0x00:0x02])[0],
            held_item=struct.unpack("<H", data[0x02:0x04])[0],
            moves=[
                struct.unpack("<H", data[0x04:0x06])[0],
                struct.unpack("<H", data[0x06:0x08])[0],
                struct.unpack("<H", data[0x08:0x0A])[0],
                struct.unpack("<H", data[0x0A:0x0C])[0],
            ],
            level=data[0x0C],
            variant_and_flags=data[0x0D],
            more_flags=data[0x0E],
            padding=data[0x0F],
        )
    
    def to_bytes(self) -> bytes:
        """Serialize to 0x10 bytes."""
        data = bytearray(0x10)
        
        struct.pack_into("<H", data, 0x00, self.species)
        struct.pack_into("<H", data, 0x02, self.held_item)
        struct.pack_into("<H", data, 0x04, self.moves[0])
        struct.pack_into("<H", data, 0x06, self.moves[1])
        struct.pack_into("<H", data, 0x08, self.moves[2])
        struct.pack_into("<H", data, 0x0A, self.moves[3])
        data[0x0C] = self.level
        data[0x0D] = self.variant_and_flags
        data[0x0E] = self.more_flags
        data[0x0F] = self.padding
        
        return bytes(data)
    
    @property
    def variant(self) -> int:
        """Get variant (for unown, spinda, arceus, etc)."""
        return self.variant_and_flags & 0x1F
    
    @property
    def is_female(self) -> bool:
        """Check if pokemon is female."""
        return bool(self.variant_and_flags & 0x20)
    
    @property
    def is_shiny(self) -> bool:
        """Check if pokemon is shiny."""
        return bool(self.more_flags & 0x02)
    
    @property
    def has_form(self) -> bool:
        """Check if pokemon has special form."""
        return bool(self.more_flags & 0x01)


@dataclass
class EventPokeExtraData:
    """
    Extra data for event pokemon (0x2C bytes).
    Used when gifting or catching special event pokemon.
    """
    unk_0: int = 0
    ot_tid: int = 0           # Original trainer TID
    ot_sid: int = 0           # Original trainer SID
    unk_1: int = 0
    location_met: int = 0
    unk_2: int = 0
    ot_name: str = ""         # 8 chars max
    encounter_type: int = 0
    ability: int = 0
    pokeball_type: int = 0    # As item number
    unk: bytes = field(default_factory=lambda: bytes(10))
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "EventPokeExtraData":
        """Parse from 0x2C bytes."""
        if len(data) < 0x2C:
            raise ValueError(f"EventPokeExtraData needs 0x2C bytes, got {len(data)}")
        
        return cls(
            unk_0=struct.unpack("<I", data[0x00:0x04])[0],
            ot_tid=struct.unpack("<H", data[0x04:0x06])[0],
            ot_sid=struct.unpack("<H", data[0x06:0x08])[0],
            unk_1=struct.unpack("<H", data[0x08:0x0A])[0],
            location_met=struct.unpack("<H", data[0x0A:0x0C])[0],
            unk_2=struct.unpack("<H", data[0x0C:0x0E])[0],
            ot_name=decode_pokemon_string(data[0x0E:0x1E], 8),
            encounter_type=data[0x1E],
            ability=data[0x1F],
            pokeball_type=struct.unpack("<H", data[0x20:0x22])[0],
            unk=data[0x22:0x2C],
        )
    
    def to_bytes(self) -> bytes:
        """Serialize to 0x2C bytes."""
        data = bytearray(0x2C)
        
        struct.pack_into("<I", data, 0x00, self.unk_0)
        struct.pack_into("<H", data, 0x04, self.ot_tid)
        struct.pack_into("<H", data, 0x06, self.ot_sid)
        struct.pack_into("<H", data, 0x08, self.unk_1)
        struct.pack_into("<H", data, 0x0A, self.location_met)
        struct.pack_into("<H", data, 0x0C, self.unk_2)
        data[0x0E:0x1E] = encode_pokemon_string(self.ot_name, 8)
        data[0x1E] = self.encounter_type
        data[0x1F] = self.ability
        struct.pack_into("<H", data, 0x20, self.pokeball_type)
        data[0x22:0x2C] = self.unk[:10].ljust(10, b"\x00")
        
        return bytes(data)


@dataclass 
class PeerPlayData:
    """
    Peer play exchange data (0x38 bytes).
    Exchanged during walker-to-walker peer play.
    """
    cur_step_count: int = 0
    cur_watts: int = 0
    padding_1: bytes = field(default_factory=lambda: bytes(2))
    unk_0: int = 0
    unk_2: int = 0
    species: int = 0          # Species of pokemon in walker
    poke_nickname: str = ""   # 11 chars max
    trainer_name: str = ""    # 8 chars max
    poke_gender_form: int = 0
    poke_is_special: int = 0  # Set if has forms: spinda, arceus, unown
    
    @classmethod
    def from_bytes(cls, data: bytes) -> "PeerPlayData":
        """Parse from 0x38 bytes."""
        if len(data) < 0x38:
            raise ValueError(f"PeerPlayData needs 0x38 bytes, got {len(data)}")
        
        return cls(
            cur_step_count=struct.unpack("<I", data[0x00:0x04])[0],
            cur_watts=struct.unpack("<H", data[0x04:0x06])[0],
            padding_1=data[0x06:0x08],
            unk_0=struct.unpack("<I", data[0x08:0x0C])[0],
            unk_2=struct.unpack("<H", data[0x0C:0x0E])[0],
            species=struct.unpack("<H", data[0x0E:0x10])[0],
            poke_nickname=decode_pokemon_string(data[0x10:0x26], 11),
            trainer_name=decode_pokemon_string(data[0x26:0x36], 8),
            poke_gender_form=data[0x36],
            poke_is_special=data[0x37],
        )


# EEPROM address constants
class EEPROMAddress:
    """Important EEPROM addresses."""
    MAGIC = 0x0000              # "nintendo" magic string
    ADC_CALIBRATION = 0x0080    # Factory ADC calibration (reliable)
    UNIQUE_ID = 0x0083          # UniqueIdentityData (reliable)
    LCD_CONFIG = 0x00AC         # LCD init commands (reliable)
    IDENTITY = 0x00ED           # IdentityData (reliable)
    HEALTH = 0x0156             # HealthData (reliable)
    COPY_MARKER = 0x016F        # Copy atomicity marker (reliable)
    
    # Graphics (language-specific)
    NUMERIC_CHARS = 0x0280      # "0123456789:-/"
    WATT_SYMBOL = 0x0420
    
    # Current route data
    ROUTE_INFO = 0x8F00
    AREA_IMAGE = 0x8FBE
    AREA_NAME = 0x907E
    POKEMON_SMALL_ANIM = 0x91BE
    POKEMON_LARGE_ANIM = 0x933E
    POKEMON_NAME = 0x993E
    
    # Special event data
    SPECIAL_FLAGS = 0xB800
    EVENT_POKEMON = 0xBA44
    EVENT_POKEMON_EXTRA = 0xBA54
    EVENT_POKEMON_SPRITE = 0xBA80
    EVENT_POKEMON_NAME = 0xBC00
    EVENT_ITEM = 0xBD40
    EVENT_ITEM_NAME = 0xBD48
    
    # Collected items/pokemon
    CAUGHT_POKEMON = 0xCE8C     # 3x PokemonSummary
    DOWSED_ITEMS = 0xCEBC       # 3x (u16 item, u16 unused)
    GIFTED_ITEMS = 0xCEC8       # 10x (u16 item, u16 unused)
    
    # Event log
    EVENT_LOG = 0xCF0C          # 24x EventLogItem
    
    # Team data
    TEAM_DATA = 0xCC00
